# Root directories
root_dir: "/nfs2/harmonization/BIDS/WRAPnew/derivatives/"
t1_root_dir: "/nfs2/harmonization/BIDS/WRAPnew"
pattern: "sub-*/ses-*/SLANT-TICVv1.2/post/FinalResult/*_T1w_seg.nii.gz"

# Statistic outputs
ai_pairs_csv: "labels/slant_ai_pairs.csv"
label_index: "labels/label_index.csv"
ticv_csv: "stats_csv/ticv_summary.csv"
brainvol_csv: "stats_csv/brain_volume.csv"
asymmetry_index_csv: "stats_csv/asymmetry_index.csv"
roi_volumes_csv: "stats_csv/roi_volumes.csv"
roi_volumes_zscore_csv: "stats_csv/roi_volumes_zscore.csv"

# ROI colour label
lut_addr: "labels/slant.label"
